// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timothy_Hsu_MVC.Data;

namespace Timothy_Hsu_MVC.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210628080254_newDb")]
    partial class newDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Timothy_Hsu_MVC.Models.ScrumStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScrumStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Not Checked Out"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Checked Out"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("Timothy_Hsu_MVC.Models.ScrumTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScrumStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ScrumUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScrumStatusId");

                    b.HasIndex("ScrumUserId");

                    b.ToTable("ScrumTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fix bug that causes crash",
                            ScrumStatusId = 1,
                            Title = "Fix bug #1235"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fix bug that causes wrong View to be shown",
                            ScrumStatusId = 1,
                            Title = "Fix bug #5425"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Write new code for new feature",
                            ScrumStatusId = 2,
                            ScrumUserId = 1,
                            Title = "Implement new feature"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The toilets must be cleaned",
                            ScrumStatusId = 1,
                            Title = "Clean toilets"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Buy a new laptop for our new employee",
                            ScrumStatusId = 3,
                            ScrumUserId = 3,
                            Title = "Buy a new laptop"
                        });
                });

            modelBuilder.Entity("Timothy_Hsu_MVC.Models.ScrumUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScrumUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bill"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tim"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alex"
                        });
                });

            modelBuilder.Entity("Timothy_Hsu_MVC.Models.ScrumTask", b =>
                {
                    b.HasOne("Timothy_Hsu_MVC.Models.ScrumStatus", "ScrumStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("ScrumStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Timothy_Hsu_MVC.Models.ScrumUser", "ScrumUser")
                        .WithMany("ScrumTasks")
                        .HasForeignKey("ScrumUserId");

                    b.Navigation("ScrumStatus");

                    b.Navigation("ScrumUser");
                });

            modelBuilder.Entity("Timothy_Hsu_MVC.Models.ScrumStatus", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Timothy_Hsu_MVC.Models.ScrumUser", b =>
                {
                    b.Navigation("ScrumTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
